### PR TITLE
deploy.pl: cleaned up

### PR DESCRIPTION
**Pull request by djzort**
as per your tweet, this now uses strict, warnings and Carp. i didnt test it on anything though, it just compiles and passes perl::critic. ive also added commands to install the requisite libraries using apt-get (at least in debian)

### CODE REVIEW

**Comment by maxandersen** [comment]
gah - seems I missed this PR comment 3 years ago ;/

**Comment by maxandersen** [comment]
I know its outdated, but applied it now as a good measure ;)

**Comment by maxandersen** [comment]
sorry again!

**Comment by djzort** [comment]
cool, i literally don't even remember what this is.

**Pull request closed without merging**
